apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: poc-project-1
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: spring-boot-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-deployment
  namespace: poc-project-1
  labels:
    app: spring-boot-app
spec:
   spec:
      containers:
        - name: spring-boot-container
          image: 723185050974.dkr.ecr.ap-south-1.amazonaws.com/sping-pet-clinic-repo
      imagePullSecrets:
      - name: regcred
