apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: poc-project
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: spring-boot-app
---
apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-app
  namespace: poc-project
spec:
  containers:
  - name: sping-boot-container
    image: 723185050974.dkr.ecr.ap-south-1.amazonaws.com/sping-pet-clinic-repo
  imagePullSecrets:
  - name: regcred
